### ISSUE TITLE
Fix corner case when file does not exist on one endpoint

### ISSUE THREAD

**Issue by ruizdesotto** [ruizdesotto/data_cliff#25]
### Description

Most of the time, the file exists on both revisions being compared. One corner case occurs when the file does not exist in one of the revs

## Tasks

Allow for the cases:

- [x] File exists in both end points
- [ ] File does not exist in one end point -> exit with code 0
- [ ] File does not exist -> output an error message

**Comment by Lhenzo** [comment]
so actually was this solving #35 like mentionned ? (i'll try it out tomorrow anyway ehe)

**Comment by ruizdesotto** [comment]
I dont think it does
