### ISSUE TITLE
[BUG] when testing the printing

### ISSUE THREAD

**Issue by ruizdesotto** [ruizdesotto/data_cliff#30]
* data_cliff version: 0.0.9
* Python version: 3.10.6
* Operating System: Ubuntu 20.04

### Description

The command `make test-all` shows a green pipeline. However there are two tests that don't behave as they should:

- [ ] FAILS `pytest tests/test_data_cliff.py::test_compare_staged_change` 
- [ ] PASSES `pytest tests/test_cli.py::test_main` 

The failure comes when comparing the output printing. Some conflict between `pytest` output and the color printing makes it fail

### Tasks

- [ ] Why does it fail?
- [ ] How to fix it so that we check the color printing

### Contributors
@ruizdesotto

**Comment by ruizdesotto** [comment]
`capsys` does not always escape the ANSI characters, so I created a fixture that would mock the print statement with stringIO to be able to retrieve those caracters.

**Comment by ruizdesotto** [comment]
@mdeboc some context here
